### ISSUE TITLE
Can’t record audio on Ubuntu 22.04

### ISSUE THREAD

**Issue by dgendill** [ppd/anki-ppd#2]
Hello, thanks for compiling this snap for the software center! I’m using Ubuntu 22.04, and just wanted to report an audio recording issue that I'm having. I’ve gone into the Ubuntu software center and given recording permissions to the application, but when I try and record audio I get this error message…

> Unable to record. Please ensure a microphone is connected, and Anki has permission to use the microphone. If other programs are using your microphone, closing them may help. Original error: ⁨No module named 'PyQt5.QtMultimedia’⁩

I tried switching to PyAudio driver and then I get this error.

> An error occurred. Please use Tools > Check Database to see if that fixes the problem.
> If problems persist, please report the problem on our support site. Please copy and paste the information below into your report.
> Anki 2.1.49 (dc80804a) Python 3.8.10 Qt 5.15.3 PyQt 5.15.4
> Platform: Linux
> Flags: frz=False ao=False sv=2
> Add-ons, last update check: 2022-05-14 09:02:31
> 
> Exception in thread Thread-4:
> Traceback (most recent call last):
> File “/usr/lib/python3.8/threading.py”, line 932, in _bootstrap_inner
> self.run()
> File “/snap/anki-ppd/5/lib/python3.8/site-packages/aqt/sound.py”, line 646, in run
> p = pyaudio.PyAudio()
> AttributeError: ‘NoneType’ object has no attribute ‘PyAudio’
> Exception in threading.excepthook:
> Exception ignored in thread started by: <bound method Thread._bootstrap of <PyAudioThreadedRecorder(Thread-4, started 140066903013120)>>
> Traceback (most recent call last):
> File “/usr/lib/python3.8/threading.py”, line 890, in _bootstrap
> self._bootstrap_inner()
> File “/usr/lib/python3.8/threading.py”, line 934, in _bootstrap_inner
> self._invoke_excepthook(self)
> File “/usr/lib/python3.8/threading.py”, line 1212, in invoke_excepthook
> local_print(“Exception in threading.excepthook:”,
> AttributeError: ‘ErrorHandler’ object has no attribute ‘flush’
> Exception ignored in sys.unraisablehook:
> AttributeError: ‘ErrorHandler’ object has no attribute ‘flush’
> 

Here’s the debug info from inside Anki application.

> Anki 2.1.49 (dc80804a) Python 3.8.10 Qt 5.15.3 PyQt 5.15.4
> Platform: Linux
> Flags: frz=False ao=False sv=2
> Add-ons, last update check: 2022-05-14 09:02:31
> 
> 
> ===Add-ons (active)===
> (add-on provided name [Add-on folder, installed at, version, is config changed])
> 
> 
> ===IDs of active AnkiWeb add-ons===
> 
> 
> ===Add-ons (inactive)===
> (add-on provided name [Add-on folder, installed at, version, is config changed])

And here's the relevant snap connections for anki

```
$ snap connections anki-ppd
Interface                                  Plug                       Slot                           Notes
audio-playback                             anki-ppd:audio-playback    :audio-playback         -
audio-record                               anki-ppd:audio-record      :audio-record             manual
```

Sorry I can't help. I'm new to building snap packages but I'm going to try to build with snapcraft and see if I can fix it.

**Comment by ppd** [comment]
Thanks for the report. Seems like it's simply missing both PyQt5.QtMultimedia’ and pyaudio packages. It needs at least one of those to work I'll add one and rebuild. 

**Edit**: You found out yourself :). I'll take a look at the PR

**Comment by ppd** [comment]
Fixed by https://github.com/ppd/anki-ppd/commit/9d21dee5d3adb58d725d0853ea08ac3c231126b4
