### ISSUE TITLE
Add "unity7" plugin to snap

### ISSUE THREAD

**Issue by k-kirill** [ppd/anki-ppd#5]
It looks like to support badge in dock for Anki snap via [libunity plugin](https://github.com/k-kirill/anki-libunity) we need the snap to include the `unity7` plugin.
More info in k-kirill/anki-libunity#8

**Comment by ppd** [comment]
For future visitors: Please use: [snapcraft.io/anki-desktop](https://snapcraft.io/anki-desktop)
