### ISSUE TITLE
Segfault on Ubuntu

### ISSUE THREAD

**Issue by hugovdm** [ppd/anki-ppd#7]
I'm not sure if this is the right place to report bugs? But it's something. I'm currently getting a segfault on Ubuntu:

```
$ anki-ppd.anki 
Preparing to run...
Qt info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. 
Segmentation fault (core dumped)
$ anki-ppd.anki --version
Preparing to run...
Anki 2.1.54
$ cat /etc/issue
Ubuntu 22.04.4 LTS \n \l

```

No idea whether the Qt wayland warning is a red herring, but I tried it out anyway:

```
$ QT_QPA_PLATFORM=wayland anki-ppd.anki 
Preparing to run...
Qt info: Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway. 
Qt warning: Could not find the Qt platform plugin "wayland" in "" 
Qt fatal: This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
 
Aborted (core dumped)
```

And I also don't know where core is dumped. Looks like it's not in the current directory or a subdir of it. (And I didn't spot a path looking for "core" in strace output either.)

**Comment by hugovdm** [comment]
This issue probably belongs at https://github.com/ankitects/anki/issues instead?

_Update: no, considering the issue is the staleness of the anki-ppd package, see below._

**Comment by hugovdm** [comment]
I found this: https://forums.ankiweb.net/t/24-04-crashes-on-sync-login/43050 - but that thread starting at the end of March 2024, I next wondered how old anki-ppd is:

```
$ snap info anki-ppd
name:      anki-ppd
<snip>
tracking:     latest/stable
refresh-date: 2023-10-06
channels:
  latest/stable:    2.1.54 2022-08-20 (8) 302MB -
  latest/candidate: ↑                           
  latest/beta:      2.1.54 2022-08-08 (8) 302MB -
  latest/edge:      2.1.49 2021-11-10 (5)  64MB -
installed:          2.1.54            (8) 302MB -
```

So it looks like anki-ppd is actually on a pretty old version, and I should perhaps switch to some fresher source.

**Comment by boukendesho** [comment]
I have created a new anki snap. Welcome to try it. https://snapcraft.io/anki-desktop

**Comment by ppd** [comment]
Sorry for the lack of communication. My main work computer, unfortunately, has become a MacBook. Please do use the snap by @boukendesho. I will archive this repository and unpublish anki-ppd.
