### ISSUE TITLE
Request to Update Anki on Snap Store to Latest Release (24.11)

### ISSUE THREAD

**Issue by gryphon2411** [ppd/anki-ppd#8]
Hello,

I noticed the current Snap version is `2.1.54` (Jun 2022), while the latest Anki release is `24.11` (Nov 2024). 

Would it be possible to update the Snap package to the newest version?

Many thanks for your time and efforts for making Anki available on the Snap Store.

**Comment by ppd** [comment]
Hi, there is a more recent snap available under a different name: https://snapcraft.io/anki-desktop

I should probably archive this repository, as I do not really have the time any more to maintain it.
